version: "3.7"

services:
    db:
        container_name: db
        image: mysql:5.7
        command: '--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password'
        restart: always
        secrets:
            - db-password
        volumes:
            - db-data:/var/lib/mysql
            - ./db/init.sql:/data/application/init.sql
        networks:
            - backnet
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD_FILE=$MYSQL_ROOT_PASSWORD_FILE
    
    backend:
        container_name: backend
        build: ./backend
        restart: always
        secrets:
            - db-password
        volumes:
            - image-data:/storage/images/
            - ./logs:/logs
            - ./backend:/code # Development Configuration
        ports:
            # - 8000:8000 # Production Port
            - 5000:5000
        depends_on:
            - db
        environment:    
            - MYSQL_USER="${MYSQL_USER}"
            - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
            - MYSQL_HOST="${MYSQL_HOST}"
            - MYSQL_DATABASE="${MYSQL_DATABASE}"
        networks:
            - backnet
            - frontnet
        # command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app # Production Configuration
    
    nginx:
        container_name: nginx
        build: ./nginx
        restart: always
        ports:
            - 80:80
        depends_on:
            - backend
        networks:
            - frontnet

volumes:
    db-data:
    image-data: 
secrets:
    db-password:
        file: ./db/password.txt
networks:
    backnet:
    frontnet:
